# EXPERIMENT NO 12.1

# fruits = ["apple", "banana", "cherry"]
# for fruit in fruits:
#     print(fruit)

# EXPERIMENT NO 12.2

# count = 0
# while count < 5:
#     print(count,end=' ')
#     count += 1

# EXPERIMENT NO 12.3

# for number in range(10):
#     if number == 5:
#         break
#     print(number,end='  ')

# EXPERIMENT NO 12.4

# for number in range(5):
#     if number == 2:
#         continue
#     print(number , end='  ')

# EXPERIMENT NO 12.5

# for i in range(4,5):
#     for j in range(1, 11):
#         product = i * j
#         print(f"{i} x {j} = {product}")

# EXPERIMENT NO 12.6

# fruits = ["apple", "banana", "cherry", "date", "fig"]
# for fruit in fruits:
#     if len(fruit) > 5:
#         print(f"{fruit} is a long fruit.")
#     else:
#         print(f"{fruit} is not a long fruit.")

# EXPERIMENT NO 12.7

# count = 0
# while count < 5:
#     if count % 2 == 0:
#         print(f"{count} is an even number.")
#     else:
#         print(f"{count} is an odd number.")
#     count += 1





