# name = "harshadaakruti"
# for i in name:
#     print(i)
#     if(i=='d'):
#         print("starting and ending ")

colors=["green" ,"yellow","orange","pink","brown"]
print(type(colors))
for color in colors:
    print(color)
    for i in color:
         print(i)


for i in range(89):
    print(i)

for i in range(8,12):
    print("the number in between 8 to 11 is ",i)

for i in range (5 , 25 , 5):
    print(i)