# PYTHON IS DYNAMICALLY TYPED OBJECT ORIENTED PROGRAMMING LANGUAGE
# CREATED BY GUIDO VAN RUSSOM IN 1991
# FEATURES OF PYTHON PROGRAMMING
#
# 1) ITS VERY SIMPLE LANGUAGE
# 2) PLATFORM INDEPENDENT
# 3) PYTHON PROVIDE VERY BIG LIBRARY SUPPORT
# 4) WE CAN CREATE WEB APPILICATION WEBSITE GAME BY USING PYTHON
