import hashlib
print("hellow")
print(34)
# MODULES AND PACKAGES --> ITS LIKE A CODE LIBRARY WHICH CAN BE USED TO BORROW THE CODE WRITTEN BY SOMEBODY ELSE
#                           IN OUR PYTHON PROGRAM
# BUILT IN MODULE --> THESE MODULES ARE READY TO IMPORT AND USED AND SHIPS WITH THE PYTHON INTERPRETER THERE IS NO
#                      ANY NEED TO INSTALL SUCH MODULE EXPLICITLY
# EXTERNAL MODULE --> THESE MODULES ARE IMPORTED FROM THIRD PARTY FILE OR CAN BE INSTALLED USING A PACKAGE MANAGER
#                      FILE OR PIP OR CONDA SINCE THESE CODE ARE WRITTEN AS SOMEONE ELSE WE CAN INSTALL DIFFERENT
#                      VERSIONS OF A SAME MODULE WITH TIME