a = "harry"
b = "bhai"
c = "1"
d = "7"
print(int(c)+ int(d)) # -->type casting explicitly
# THE CONVERSION OF ONE DATA TYPE TO ANOTHER DATA TYPE ,DONE VIA DEVELOPER OR PROGRAMMERS INTERVENTION OR
# MANUALLY AS PER THE REQUIREMENT,IS KNOW AS EXPLICITE TYPECASTING CONVERSION
# IT CAN BE HELP WITH THE HELP OF PYTHOND BUILT IN TYPE CONVERSION FUNCTIONS SUCH AS INT(),FLOAT(),HEX(),
# OCT(),STR() ETC.
# EXAMPLE
k = int(c)
l = int(d)
print(k+l,"the addition of two number is ")
# IMPLICITE TYPECASTING
# DATA TYPES IN PYTHON DO NAT HAVE THE SAME LEVEL I.E ORDERING OF DATA TYPES IS NOT SAME IN PYTHON .SOME OF DATA TYPES HAVE
# HAVE HIGHER ORDER AND SOME HAVE LOWER ORDER WHILE PERFORMING ANY OPERATION ON VARIABLES WITH DIFFERENT DATA TYPES
# IN PYTHON ONE OF THE VARIABLES DATA TYPES WILL BE CHANGED TO THE HIGHER DATA TYPE .ACCORDING TO THE LEVEL ONE DATA
# TYPE IS CONVERTED INTO OTHER BY THE PYTHON INTERPRETER ITSELF(AUTOMATICALLY) THIS IS CALLED IMPLICITLY TYPECASTING
# EXAMPLE
c= 1.9
print("the type of c is ",type(c))
d=8
print("the type of d is ",type(d))
e=c+d
print("the type of e is ",type(e))
print("the addition of any two number by having implicite type casting",e)